### PR TITLE
prereqs: Remove wrappy3

### PR DESCRIPTION
**Pull request by zjp**
Since we're on a kick of cleaning up the repo, I don't think this library is used anymore.

`rg wrappy` brings up the deleted files and the following:

```
src/bundles/md_crds/src/dcd/MDToolsMarch97/md_AtomGroup.py
17:# Update for wrappy2.

src/bundles/md_crds/src/dcd/MDToolsMarch97/md_DCD.py
32:# Update for wrappy2.
```

### CODE REVIEW

**Comment by tomgoddard** [comment]
Greg, can we remove wrappy3 from the ChimeraX git repository?  Nice work making a pull request Zach!  Good to learn how to handle pull requests.

**Comment by zjp** [comment]
I think the pull request mechanism is great! Not just for outside developers but to have a convenient interface for RBVI programmers to get a second pair of eyes on changes they're unsure about, like I'm not quite sure about this one. :)

**Comment by tomgoddard** [comment]
Sure.  I've made a personal copy, since it has lots of examples of how 
to use the Python internals.  But it is not needed anymore.  We should 
look at standardizing our Python-C++ binding with PyBind11 that Tristan 
uses.

     -- Greg

**Comment by zjp** [comment]
Great!

**Pull request merged**
