### PR TITLE
Build: Move vsvars{,2015}.sh to mk folder

### PR DESCRIPTION
**Pull request by zjp**
The only beneficial thing in this PR is housekeeping; I just think these files belong in /mk

### CODE REVIEW

**Comment by tomgoddard** [comment]
Not sure this change makes sense.  The mk subdirectory is for common makefiles.  The vsvars shell scripts are to set up Windows compilers under cygwin to do builds.

**Comment by zjp** [comment]
Should it always be for common makefiles, or could it be for setting up the environment regardless of platform?

**Comment by tomgoddard** [comment]
The directory name mk does not suggest it is generic build setup.  Maybe build related scripts could go into a new subdirectory.  Greg has mostly managed builds.

**Comment by gregcouch** [comment]
That's not appropriate.  The mk folder is for make include files.

**Pull request closed without merging**
